from typing import List, Dict, Optional, Set, Any
from datetime import datetime
from pydantic import BaseModel, Field
from enum import Enum

class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"

class ToolType(str, Enum):
    SAST = "SAST"
    DAST = "DAST"
    SCA = "SCA"
    IAC = "IAC"
    CONTAINER = "CONTAINER"
    SECRET = "SECRET"

class CorrelationStatus(str, Enum):
    ACTIVE = "ACTIVE"
    FIXED = "FIXED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    SUPPRESSED = "SUPPRESSED"

class CodeLocation(BaseModel):
    file_path: str
    line_start: int
    line_end: int
    snippet: Optional[str] = None

class EndpointLocation(BaseModel):
    url: str
    method: Optional[str] = "GET"
    parameter: Optional[str] = None

class UnifiedFinding(BaseModel):
    """
    The single, normalized schema for all security findings.
    """
    id: str # Unique fingerprint (hash of title + location)
    title: str
    description: str
    severity: Severity
    
    # Meta
    tool_source: str # e.g., "Semgrep"
    tool_type: ToolType
    
    # Location Data (The bridge between SAST and DAST)
    code_location: Optional[CodeLocation] = None
    endpoint_location: Optional[EndpointLocation] = None
    
    # Correlation Data
    related_findings: List[str] = [] # IDs of other findings (e.g., DAST confirming SAST)
    correlation_score: int = 0 # 0-100 confidence score
    is_confirmed_by_other_tool: bool = False
    
    # Enrichment
    cwe_id: Optional[str] = None
    cve_id: Optional[str] = None
    remediation_steps: Optional[str] = None
    ai_explanation: Optional[str] = None # Generated by Gemini
    
    # Technical Details
    raw_data: Dict[str, Any] = {} # The original tool output
    tags: Set[str] = set() # e.g., {"xss", "auth", "django"}

    def fingerprint(self) -> str:
        """Generates a deterministic hash for deduplication."""
        import hashlib
        # Use title and location to identify uniqueness
        loc = ""
        if self.code_location:
            loc += f"{self.code_location.file_path}:{self.code_location.line_start}"
        if self.endpoint_location:
            loc += f"{self.endpoint_location.url}"
        
        base = f"{self.title}|{self.tool_source}|{loc}"
        return hashlib.sha256(base.encode()).hexdigest()