# Use the official NGINX image from Docker Hub
FROM nginx:1.25-alpine

# Remove the default NGINX configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom, hardened nginx.conf file into the container
# This is the file that contains all our security rules and proxy logic
COPY nginx.conf /etc/nginx/conf.d/

