import pydantic
from typing import Optional
# --- FIX: Import ConfigDict and the to_camel utility ---
from pydantic import ConfigDict
from pydantic.alias_generators import to_camel
# ----------------------------------------------------

class UserBase(pydantic.BaseModel):
    """
    Base user model with fields common to all user representations.
    """
    email: pydantic.EmailStr
    full_name: Optional[str] = None
    is_active: bool = True
    is_admin: bool = False

class UserCreate(UserBase):
    """
    Model used when creating a new user. Includes the password.
    This model is used for API input.
    """
    password: str

class UserUpdate(pydantic.BaseModel):
    """
    Model used when updating an existing user. All fields are optional.
    """
    email: Optional[pydantic.EmailStr] = None
    full_name: Optional[str] = None
    is_active: Optional[bool] = None
    is_admin: Optional[bool] = None
    password: Optional[str] = None

class User(UserBase):
    """
    Model used when reading user data (e.g., returning from API).
    It should NOT include the password.
    We add 'id' here, which is typically generated by the database.
    """
    id: str # In a real DB, this might be an int or UUID
    
    # --- FIX: Use the Pydantic v2 ConfigDict syntax ---
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True
    )
    # --------------------------------------------------


class UserInDB(User):
    """
    Model representing a user as stored in our "database".
    This includes the hashed password for authentication checks.
    """
    hashed_password: str

class Token(pydantic.BaseModel):
    """
    Model for the JWT access token returned upon successful login.
    """
    access_token: str
    token_type: str

class LoginResponse(pydantic.BaseModel):
    """
    The full response for a successful login, including
    the token and the user's details.
    """
    access_token: str
    token_type: str = "bearer"
    user: User


class TokenData(pydantic.BaseModel):
    """
    Model for the data (payload) encoded within the JWT.
    This is what we get back after decoding a token.
    """
    email: Optional[pydantic.EmailStr] = None